name: Feeds

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  feeds:
    runs-on: ubuntu-latest
    name: Build static feeds site
    steps:
      - name: Run Action
        uses: llun/feeds@main
        with:
          customDomain: feeds.llun.dev
